export const REACT_QUERY_KEYS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_SHOW: "GET_PRODUCTS_SHOW",
  GET_CART: "GET_CART",
  GET_CART_SHIPPING_OPTIONS: "GET_CART_SHIPPING_OPTIONS",
  GET_LOCATIONS_INDEX: "GET_LOCATIONS_INDEX",
};
